#!/usr/bin/python
#-*- coding: utf-8 -*-

"""Triangular, pentagonal, and hexagonal
Problem 45
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal."""

def triangle(number):
    return int(number * (number +1)/2)

def pentag(number):
    return int(number*(3*number-1)/2)

def hexag(number):
    return int(number*(2*number-1))




pentagset = set(pentag(i) for i in range(100000))
hexagset  = set(hexag(i) for i in range(100000))
for i in range(100000):
    t = triangle(i)
    if t in pentagset and t in hexagset and t > 40755:
        print t







    



    
